name: Southshire
url: southshire.wiki
title: Southshire
email: cranite@protonmail.com
description: The official website for Southshire, Commonwealth.
feed_description: The official website for Southshire, Commonwealth.
meta_description: "Southshire, Commonwealth. (Official)"

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
